name: Airport Parking Availability Scraper

# on:
#   schedule:
#     - cron: '0 * * * *' # Run every hour
#   workflow_dispatch: # Allow manual triggering

on:
  push:
    branches: ['main']
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape-and-notify:
    environment: KAKAO
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install puppeteer

      - name: Scrape Parking Availability
        run: |
          node index.js > parking_results.txt

      - name: Send KakaoTalk Notification
        env:
          KAKAO_ACCESS_TOKEN: ${{ secrets.KAKAO_ACCESS_TOKEN }}
        run: |
          # Use Kakao API to send message
          curl -X POST "https://kapi.kakao.com/v2/api/talk/memo/default/send" \
          -H "Authorization: Bearer $KAKAO_ACCESS_TOKEN" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "template_object={
            'object_type': 'text',
            'text': '$(cat parking_results.txt)',
            'link': {
              'web_url': 'https://github.com/your-username/your-repo'
            }
          }"
