name: Airport Parking Availability Scraper

# on:
#   schedule:
#     - cron: '0 * * * *' # Run every hour
#   workflow_dispatch: # Allow manual triggering

on:
  push:
    branches: ['main']
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape-and-notify:
    environment: KAKAO
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install puppeteer

      - name: Scrape Parking Availability
        run: |
          node index.js > parking_results.txt

      - name: Update README with Parking Results
        run: |
          echo "## Parking Availability Update" > README.md
          echo "\`\`\`" >> README.md
          cat parking_results.txt >> README.md
          echo "\`\`\`" >> README.md

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update parking availability results"
          git push
